# Generated by Django 5.2.4 on 2026-09-19 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.CharField(help_text='Identificador de la película en la API externa (imdbID)', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
                ('nota', models.PositiveSmallIntegerField(blank=True, help_text='Calificación personal, por ejemplo de 1 a 5', null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favoritas',
                'ordering': ['-fecha_agregado'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'id_pelicula'), name='unica_favorita_por_usuario'), models.CheckConstraint(condition=models.Q(('nota__isnull', True), models.Q(('nota__gte', 1), ('nota__lte', 5)), _connector='OR'), name='nota_favorita_entre_1_y_5')],
            },
        ),
    ]
