# Generated by Django 5.2.4 on 2026-09-18 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorita',
            constraint=models.CheckConstraint(condition=models.Q(('nota__isnull', True), models.Q(('nota__gte', 1), ('nota__lte', 10)), _connector='OR'), name='nota_favorita_entre_1_y_10'),
        ),
    ]
